In [1]:
# import libraries
import numpy as np

In [2]:
# define a multi - dimensional array
arr = np.array([[2,3],[4,5]])
arr

array([[2, 3],
       [4, 5]])

# Hadamard (element - wise) Vs Matrix Products

In [3]:
#define to arrays with arrange and reshape
arr1 = np.arange(0,12,2).reshape(2,3)
arr2 = np.arange(10,40,10).reshape(3,1)
print(arr1)
print(arr2)

[[ 0  2  4]
 [ 6  8 10]]
[[10]
 [20]
 [30]]


In [4]:
# Now do a matrix multiplication
arr1@arr2

array([[160],
       [520]])

In [5]:
# do an element wise (or Hadamard) product
# first defines two 3x3 integer matrices
arr1 = np.random.randint(low=2, high=10, size=(3,3))
arr2 = np.random.randint(low=2, high=5, size=(3,3))

print(arr1)
print(arr2)
# and then multiple each element of one with every element of the second
print(arr1*arr2)

[[7 4 8]
 [6 9 8]
 [8 5 2]]
[[4 2 4]
 [4 3 2]
 [4 2 4]]
[[28  8 32]
 [24 27 16]
 [32 10  8]]


In [6]:
# and create a boolean array (i.e. an array with Boolean elements) based on specific condition
arr3 = arr1*arr2

arr3 > 20

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]], dtype=bool)

# Slicing and Filtering

In [7]:
# Boolean indexing
# Lets's say we want to create a sub array from the elements that are greater than 20

# remember arr3 is NOT the Boolean but the Hadamard product
print(arr3)
arr4 = arr3[arr3 > 20]

# arr4 is an one dimensional array with only the elements of arr3 greater than 20
print(arr4)

[[28  8 32]
 [24 27 16]
 [32 10  8]]
[28 32 24 27 32]


In [8]:
# let's see slicing in one dimensional arrays
arr1 = np.array([1,2,3,4,5])

# select 2nd and 3rd columns only. Remember array elements start from zero. (i.e. zero is the index of 
# the first element). The notation is <array>[start(inclusive), stop(exclusive)], that means the element 
# specified in the starting index is included, the element in the stopping index is not included. 
sub1 = arr1[2:3]
sub1

array([3])

In [9]:
# Let's see slicing in multi dimensional arrays

arr1 = np.random.randint(1,4,size=(2,3))
print('Original Array:')
print(arr1)
# create a sub array of 1x3. Here the first argument refers to the rows selected, the second argument to
# the columns selected.
print('Sub-Array')
sub1 = arr1[:1,:2]
print(sub1)

Original Array:
[[3 2 3]
 [3 2 3]]
Sub-Array
[[3 2]]


In [10]:
# Now let's change the value of an element in the sub array

# change the value of the second item
sub1[0,1] = 32

# and let's see what happened in the sub-array and the original array: they BOTH changed.
# this means that the sub-array is actually a view of the original; hence modifying the sub array
# actually we are modifying the parent.
print(sub1)
print(arr1)

[[ 3 32]]
[[ 3 32  3]
 [ 3  2  3]]


In [11]:
# Now let's select specific columns of a row

arr1 = np.random.randint(1,5, size=(3,3))
print(arr1)

# select second row, columns 1 and 3 only
subarr2 = arr1[1:2, [0,2]]
subarr2

[[4 1 2]
 [2 2 1]
 [2 1 3]]


array([[2, 1]])

In [13]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]
